Repository sristy17/Codess-Hackathon, pull requests merged in 2024-08, with the labels that each got.

#6 Updated Community Section
  app.js
  public/css/style.css
  public/css/style_community.css
  views/pages/community.ejs
  views/pages/donation.ejs
  views/pages/job-application.ejs
  views/pages/submit-story.ejs
Labels: website

#13 [TASK]: added the chatbot
  chatbot/chatbot.py
Labels: enhancement, chatbot

#17 [DOC]: added the application description and objective
  README.md
Labels: documentation, maintainance

#18 [DOCS]: added future scope description
  README.md
Labels: documentation
